server:
  port: 8080
  ssl:
    key-store: E:\https\6319691_huanming.top_tomcat\6319691_huanming.top.pfx
    key-store-type: PKCS12
    key-store-password: 0bU03Gfa
spring:
  application:
    name: system
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  redis:
    host: localhost
    port: 6379
    database: 2
  session:
    store-type: redis
  # 修改默认的静态寻址资源目录 多个使用逗号分隔
  resources:
    static-locations: classpath:/static/
  #数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weshare?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    # 静态文件请求匹配方式
    static-path-pattern: /**
    view:
      prefix: /page/
      suffix: .html

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#开启knife4j调试  https://localhost:8080/doc.html
knife4j:
  enable: true
  production: false


feign:
  client:
    config:
      default:
        connectTimeout: 5000 #连接超时配置
        readTimeout: 10000 #执行超时配置
#日志
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: WARN
  #  在当前项目下生成日志文件
  file:
    name: system.log