#使用""表示字符串，否则0开头视为八进制
weshare:
  #工作机器ID(long)
  workerId: 12
  #序列号(long)
  datacenterId: 16
  #磁盘文件存储路径
  upload-dir: /home/liuxianchun/weshare/
  #访问文件路径(虚拟路径)
  file-dir: /file/**
  #非公开文件路径
  file-store: /home/liuxianchun/FileStore/

server:
  port: 7100
  servlet:
    context-path: /

spring:
  application:
    name: file-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #配置nacos地址
  elasticsearch:
    rest:
      uris: http://localhost:9200
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/weshare?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    # 静态文件请求匹配方式
    static-path-pattern: /**
  resources:
    # 修改默认的静态寻址资源目录 多个使用逗号分隔
    static-locations: classpath:/static/
  servlet:
    multipart:
      max-request-size: 800MB
      max-file-size: 800MB
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 10000
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true  #消息发送失败则通知生产者
    listener:
      simple:
        acknowledge-mode: manual   #手动应答消息
        concurrency: 500    #消费端最小并发数
        max-concurrency: 10000    #消费端最大并发数
        prefetch: 5000   #一次请求中预处理的消息数

#开启knife4j调试  http://localhost:7100/doc.html
knife4j:
  enable: true
logging:
  #  在当前项目下生成日志文件
  file:
    name: file.log

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
